### Site Settings ###
title               : "Using Blockchain"
description         : >-
                      Making blockchain real
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : UsingBlockchain/usingblockchain.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - pages/privacy.md
  - pages/terms-of-service.md


### Author Info ###
author:
  name              : Using Blockchain
  image             : http://yourdlt.tools/logo-yourdlt-192x192.png
#  behance           : your_username
# dribbble          : your_username
  email             : info@ubc.digital
  facebook          : UBCDigital
  github            : UsingBlockchain
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : ubc-digital
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : ubc.digital
# twitch            : your_username
  twitter           : UBC_Digital
# vimeo             : your_username
  youtube           : channel/UCnyWf1c2Gt8XjwliO-jz6gA
# keybase           : your_username
  website           : https://ubc.digital

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-EGN3KH237W


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
